### ISSUE TITLE
Discuss: rework ThemeRegistry.Current

### ISSUE THREAD

**Issue by wolframhaussig** [Assorted-Development/winforms-themes#10]
With the rework to a Builder pattern, a discussion came up for `ThemeRegistry.Current`:  https://github.com/Assorted-Development/winforms-themes/pull/6#issuecomment-1666193187

> We should, at some point, reconsider the necessity of ThemeRegistry.Current since it's not set automatically at the moment and could be easily confused with a property that always holds the current applications' theme - especially since, with this issue, it doesn't get set automatically anymore at all.

For the ThemeRegistry, we already use a specialised holder class `ThemeRegistryHolder`, maybe this would be a solution

**Comment by wolframhaussig** [comment]
Before discussing our options we may need to define what our requirements are:
1. The current solution allows to have multiple `ThemeRegistry`s (when not using `ThemeRegistryHolder.ThemeRegistry`) - each with their own `Current` theme.
2. The user should be able to use their own way of publishing the `Current` them (e.g. `Microsoft.Extensions.DependencyInjection`)
3. It should be clean code (obviously)
4. It should be easy to understand for a user
5. Do not add another dependency to the library (if possible)
6. ...

So what are our options:
a) The most obvious option is to do nothing at all: Remove the `Current` property and rely on the using application to handle everything. Most likely, this would mean removing `ThemeRegistryHolder` too for the same reasons.

b) Add a `ThemeHolder` class to the project. This would be the same as `ThemeRegistryHolder`. It extracts the logic for the current theme from the `IThemeRegistry` and allows users without other options to access the current theme easily.

c) We could keep `ThemeRegistry.Current` but make it more explicit by adding a `SetCurrentSelector(Func<IThemeRegistry, ITheme> selector)` to the builder. If this was used to set a selectorfor the current theme, `Current` will return the theme as selected by this function. If no function was provided, this would raise an error. This way, callers can still access any theme, but `Current` would return the current theme in all cases. Maybe the function could also be an interface also providing a `CurrentChanged` event to notify the registry when the current theme changes. This way, `Current` would not need to call the function continuously.

d) ...

**Comment by Nockiro** [comment]
Sooo.. I think requirement 1 is nice, but not that necessary since most applications won't have more than one theme applied to them at any given time. At least I can't think of any reason for that, but I'm happy to read any from you :smile:.
I agree with 2. to 5., though. Requirement 6 would (probably obvious) be that we even can apply more than one theme (not at once, but in general) to an application and therefore might still need the `Current` property or something like it.   
  
With that said: If we want to provide a `Current`, we are also responsible for it to return the real current theme at all times.
If we don't, we invite confusion and a lot of potential oversight (even if by the users) in regards to theming behavior.  
I also do prefer keeping `Current`, so that would remove option a).  
  
Option c) looks a bit complex (especially if we don't _really_ need multiple `ThemeRegistry`s), Option b) still lacks the automatic behavior I described above or would make it way harder to implement imho.   
  
So I'd propose kind of a middle ground option d):  
We could introduce an `Apply(ITheme)` inside `IThemeRegistry` that calls `ITheme.Apply` and lets `Current` return this theme, so that everyone who wants to use `Current` can have an automatic way built-in to really handle everything whereas users that want more flexibility still can call `Apply` on the `ITheme`.
  
What do you think?

**Comment by wolframhaussig** [comment]
Okay, so far we are aligned in regards to the requirements. The first topic was not a hard dependency but a nice to have (and no, I have no usecase for that).


Let's focus on the options (c) and (d) for now:
> Option c) looks a bit complex (especially if we don't really need multiple ThemeRegistrys)

What do you mean with complex? The easiest implementation (as I said, we could improve this with an interface providing Change detection) would be:
1. Update `ThemeRegistryBuilder` to allow setting a function `Func<IThemeRegistry, ITheme>`
2. Update `IThemeRegistry.Current` to not having a setter and the getter calls the function with itself as parameter and returns the result of the function call
3. a simple function impl could look like
```csharp
private ITheme GetCurrentTheme(IThemeRegistry registry) {
   //get current settings from config
   ThemeCapabilities caps = ...;
   //return the current theme
   return registry.Get(caps);
}
```

> We could introduce an Apply(ITheme) inside IThemeRegistry that calls ITheme.Apply and lets Current return this them

Where does the ThemeRegistry get all the forms from that the theme should get applied to? We shouldn't expect all applications to have a crentral registry of all forms and even then, `Apply(ITheme)` would need to get the forms passed as parameter. It seems to me that you just do a `SetCurrentTheme()` here.

**Comment by Nockiro** [comment]
> > Option c) looks a bit complex (especially if we don't really need multiple ThemeRegistrys)
> 
> What do you mean with complex? The easiest implementation (as I said, we could improve this with an interface providing Change detection) would be:
> 
> 1. Update `ThemeRegistryBuilder` to allow setting a function `Func<IThemeRegistry, ITheme>`
> 2. Update `IThemeRegistry.Current` to not having a setter and the getter calls the function with itself as parameter and returns the result of the function call
> 3. a simple function impl could look like
> 
> ```cs
> private ITheme GetCurrentTheme(IThemeRegistry registry) {
>    //get current settings from config
>    ThemeCapabilities caps = ...;
>    //return the current theme
>    return registry.Get(caps);
> }
> ```
> 

What I meant with complex is (but maybe I just think in the wrong direction) that the user doesn't have a simple way to just set a Theme and have it returned by `Current` as the current theme. The user would always be forced to provide some kind of lookup table (or something similar).  
But I would be completely fine with this solution if we don't find anything less complex😄 

> > We could introduce an Apply(ITheme) inside IThemeRegistry that calls ITheme.Apply and lets Current return this them
> 
> Where does the ThemeRegistry get all the forms from that the theme should get applied to? We shouldn't expect all applications to have a crentral registry of all forms and even then, `Apply(ITheme)` would need to get the forms passed as parameter.

Maybe my signature example was a bit to simplified, what I meant was to just give a possibility to "forward" the call via `IThemeRegistry` - it could also mean providing something like `Apply(ITheme, Form, [ThemeOptions]`.

**Comment by wolframhaussig** [comment]
I will open a PR with my proposed change and we can discuss the pro and contra there.
