### ISSUE TITLE
[FEATURE] Update control library

### ISSUE THREAD

**Issue by wolframhaussig** [Assorted-Development/winforms-themes#23]
**Is your feature request related to a problem? Please describe.**
Upgrade the control library and add support for everything added to the lib: https://github.com/Assorted-Development/winforms-stylable-controls/compare/v0.1.0...latest

| new `winforms-stylable-controls` feature | link to issue/PR |
| -- | -- |
| Removed `StylableToolStrip` | https://github.com/Assorted-Development/winforms-stylable-controls/pull/7 |
| Added `StylableGroupBox` | https://github.com/Assorted-Development/winforms-stylable-controls/pull/47 |
| Added `StylableMessageBox` | https://github.com/Assorted-Development/winforms-stylable-controls/pull/48 |
| Added `StylableInputBox` | https://github.com/Assorted-Development/winforms-stylable-controls/pull/50 |
| Replace `ForeColor` by separate settings `HintForeColor` and `TextForeColor` for `StylableTextBox` | https://github.com/Assorted-Development/winforms-stylable-controls/pull/22 |

**Comment by Blekkykla1** [comment]
> **Is your feature request related to a problem? Please describe.**
> Upgrade the control library and add support for everything added to the lib: https://github.com/Assorted-Development/winforms-stylable-controls/compare/v0.1.0...latest
>
